#pragma once

// Generated by tools\Build-DzjsTrainerRelease.ps1 from the signed release driver.
static const wchar_t kJiYuTestSignerSubject[] = L"JiYuTrainerDriver-Yunsjxh";
static const wchar_t kJiYuTestSignerThumbprint[] = L"FAD5B733E64A78E736DCB071B7750E55B16347BC";
