#pragma once

#define JDRV_DEVICE_TYPE 0x8338UL

#define JDRV_IOCTL_FUNCTION_QUERY_VERSION 0x800UL
#define JDRV_IOCTL_FUNCTION_INIT_PARAM 0x801UL
#define JDRV_IOCTL_FUNCTION_INIT_SELF_PROTECT 0x802UL
#define JDRV_IOCTL_FUNCTION_KILL_PROCESS 0x803UL
#define JDRV_IOCTL_FUNCTION_SUSPEND_PROCESS 0x804UL
#define JDRV_IOCTL_FUNCTION_RESUME_PROCESS 0x805UL
#define JDRV_IOCTL_FUNCTION_SHUTDOWN 0x806UL
#define JDRV_IOCTL_FUNCTION_REBOOT 0x807UL
#define JDRV_IOCTL_FUNCTION_CLIENT_QUIT 0x808UL
#define JDRV_IOCTL_FUNCTION_UNINIT 0x809UL
#define JDRV_IOCTL_FUNCTION_READ_EVENTS 0x80AUL
#define JDRV_IOCTL_FUNCTION_HEARTBEAT 0x80BUL
#define JDRV_IOCTL_FUNCTION_DRIVER_GUARD_CONFIG 0x80CUL
#define JDRV_IOCTL_FUNCTION_DRIVER_GUARD_QUERY 0x80DUL

#define CTL_QUERY_VERSION \
    CTL_CODE(JDRV_DEVICE_TYPE, JDRV_IOCTL_FUNCTION_QUERY_VERSION, METHOD_BUFFERED, FILE_READ_ACCESS)
#define CTL_INITPARAM \
    CTL_CODE(JDRV_DEVICE_TYPE, JDRV_IOCTL_FUNCTION_INIT_PARAM, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define CTL_INITSELFPROTECT \
    CTL_CODE(JDRV_DEVICE_TYPE, JDRV_IOCTL_FUNCTION_INIT_SELF_PROTECT, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define CTL_KILL_PROCESS \
    CTL_CODE(JDRV_DEVICE_TYPE, JDRV_IOCTL_FUNCTION_KILL_PROCESS, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define CTL_SUSPEND_PROCESS \
    CTL_CODE(JDRV_DEVICE_TYPE, JDRV_IOCTL_FUNCTION_SUSPEND_PROCESS, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define CTL_RESUME_PROCESS \
    CTL_CODE(JDRV_DEVICE_TYPE, JDRV_IOCTL_FUNCTION_RESUME_PROCESS, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define CTL_SHUTDOWN \
    CTL_CODE(JDRV_DEVICE_TYPE, JDRV_IOCTL_FUNCTION_SHUTDOWN, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define CTL_REBOOT \
    CTL_CODE(JDRV_DEVICE_TYPE, JDRV_IOCTL_FUNCTION_REBOOT, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define CTL_CLIENT_QUIT \
    CTL_CODE(JDRV_DEVICE_TYPE, JDRV_IOCTL_FUNCTION_CLIENT_QUIT, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define CTL_UNINIT \
    CTL_CODE(JDRV_DEVICE_TYPE, JDRV_IOCTL_FUNCTION_UNINIT, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define CTL_READ_EVENTS \
    CTL_CODE(JDRV_DEVICE_TYPE, JDRV_IOCTL_FUNCTION_READ_EVENTS, METHOD_BUFFERED, FILE_READ_ACCESS)
#define CTL_HEARTBEAT \
    CTL_CODE(JDRV_DEVICE_TYPE, JDRV_IOCTL_FUNCTION_HEARTBEAT, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define CTL_DRIVER_GUARD_CONFIG \
    CTL_CODE(JDRV_DEVICE_TYPE, JDRV_IOCTL_FUNCTION_DRIVER_GUARD_CONFIG, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define CTL_DRIVER_GUARD_QUERY \
    CTL_CODE(JDRV_DEVICE_TYPE, JDRV_IOCTL_FUNCTION_DRIVER_GUARD_QUERY, METHOD_BUFFERED, FILE_READ_ACCESS)
