#pragma once

// Generated by tools\Build-JiYuTrainerRelease.ps1 from the signed release driver.
static const wchar_t kJiYuTestSignerSubject[] = L"JiYuTrainerDriver-Yunsjxh";
static const wchar_t kJiYuTestSignerThumbprint[] = L"5AEB3FBF2F3CF3470CF0557A333E5F7E1561258D";
