[CmdletBinding()]
param(
    [string]$CertificateThumbprint,
    [string]$TimestampUrl
)

$ErrorActionPreference = 'Stop'

$solutionRoot = Split-Path $PSScriptRoot -Parent
$driverProject = Join-Path $solutionRoot 'JiYuTrainerDriver\JiYuTrainerDriver.vcxproj'
$driverOutput = Join-Path $solutionRoot 'Release\JiYuTrainerDriver.sys'
$driverFallback = Join-Path $solutionRoot 'JiYuTrainerDriver\Release\JiYuTrainerDriver.sys'
$driverPackageOutput = Join-Path $solutionRoot 'Release\JiYuTrainerDriver\JiYuTrainerDriver.sys'
$pinHeader = Join-Path $solutionRoot 'JiYuTrainer\DriverSignerPin.h'
$msbuild = (Get-Command msbuild.exe -ErrorAction Stop).Source

& $msbuild $driverProject '/t:Rebuild' '/p:Configuration=Release' '/p:Platform=x64' "/p:SolutionDir=$solutionRoot\" '/m' '/v:minimal'
if ($LASTEXITCODE -ne 0) { throw "Driver build failed with exit code $LASTEXITCODE" }

$driverCandidates = @($driverOutput, $driverFallback, $driverPackageOutput) |
    Where-Object { Test-Path -LiteralPath $_ } |
    ForEach-Object { Get-Item -LiteralPath $_ } |
    Sort-Object LastWriteTime -Descending
if ($driverCandidates.Count -eq 0) { throw "Driver output was not found" }
$driverOutput = $driverCandidates[0].FullName

if ($CertificateThumbprint) {
    $signtool = (Get-Command signtool.exe -ErrorAction Stop).Source
    $signArgs = @('sign', '/sha1', $CertificateThumbprint, '/fd', 'SHA256')
    if ($TimestampUrl) { $signArgs += @('/tr', $TimestampUrl, '/td', 'SHA256') }
    $signArgs += $driverOutput
    & $signtool @signArgs
    if ($LASTEXITCODE -ne 0) { throw "Driver signing failed with exit code $LASTEXITCODE" }
}
else {
    Write-Host ''
    Write-Host 'Driver is built. Sign the .sys with your release or test certificate now:' -ForegroundColor Yellow
    Write-Host "  $driverOutput" -ForegroundColor Yellow
    [void](Read-Host 'After signing is complete, press Enter to verify and package the release')
}

$signature = Get-AuthenticodeSignature -LiteralPath $driverOutput
if ($null -eq $signature.SignerCertificate) { throw "Driver has no embedded signature: $driverOutput" }
$subject = $signature.SignerCertificate.Subject -replace '^CN=', ''
if ($subject.Length -ge 2 -and $subject.StartsWith('"') -and $subject.EndsWith('"')) {
    $subject = $subject.Substring(1, $subject.Length - 2)
}
if ([string]::IsNullOrWhiteSpace($subject)) { throw 'Unable to read the leaf certificate subject' }
$thumbprint = ($signature.SignerCertificate.Thumbprint -replace '[^0-9A-Fa-f]', '').ToUpperInvariant()
if ($thumbprint.Length -ne 40) { throw "Unable to read the leaf certificate SHA-1 thumbprint" }
$cppSubject = $subject.Replace('\', '\\').Replace('"', '\"')

$header = @"
#pragma once

// Generated by tools\Build-JiYuTrainerRelease.ps1 from the signed release driver.
static const wchar_t kJiYuTestSignerSubject[] = L"$cppSubject";
static const wchar_t kJiYuTestSignerThumbprint[] = L"$thumbprint";
"@
[IO.File]::WriteAllText($pinHeader, $header + [Environment]::NewLine, [Text.UTF8Encoding]::new($false))

Write-Host "Verified driver signer: $subject" -ForegroundColor Green
Write-Host "Pinned signer thumbprint: $thumbprint" -ForegroundColor Green

$packageArgs = @{ DriverPath = $driverOutput }
if ($CertificateThumbprint) {
    $packageArgs.CertificateThumbprint = $thumbprint
    if ($TimestampUrl) { $packageArgs.TimestampUrl = $TimestampUrl }
}
& (Join-Path $PSScriptRoot 'Complete-DriverSigning.ps1') @packageArgs
if ($LASTEXITCODE -ne 0) { throw "Release packaging failed with exit code $LASTEXITCODE" }
